baseUrl = "https://www.qc-podcast.com"
languageCode = "en-us"
title = "QC-Podcast - A Questionable Content Podcast"

relativeURLs = true

paginate = 10

#Site Params
[params]
  description = "QC-Podcast - A Questionable Content Podcast"
  logo = "images/site_logo.png"
  twitterUser = "qc-podcast"
  twitterURL = "https://twitter.com/qc-podcast"
  copyright = ""
  episodeBucket = "https://eps-dot-qcpodcast-201423.appspot.com/dl"
  rssFeed = "https://feeds.feedburner.com/qc-podcast"
  itunesURL = "https://itunes.apple.com/us/podcast/google-cloud-platform-podcast/id1053299163"
  stitcherURL = "http://www.stitcher.com/podcast/google-cloud-platform-podcast?refid=stpr"
  googleMusicURL = "https://play.google.com/music/m/Iqkxpgvsbeejmz6d3g77qabpvme?t=Google_Cloud_Platform_Podcast"
  emailFBURL = "https://feedburner.google.com/fb/a/mailverify?uri=GcpPodcast&loc=en_US"
  youtubeURL = "https://www.youtube.com/playlist?list=PLIivdWyY5sqJOTOszXDZh3XustjvTsrmQ"


[taxonomies]
  category = "categories"